<?php

namespace Ensat\GraduateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * POSTERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class POSTERepository extends EntityRepository
{
}
