<?php

namespace Proxies\__CG__\Ensat\GraduateBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class EVENEMENT extends \Ensat\GraduateBundle\Entity\EVENEMENT implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setIntitule($intitule)
    {
        $this->__load();
        return parent::setIntitule($intitule);
    }

    public function getIntitule()
    {
        $this->__load();
        return parent::getIntitule();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDate($date)
    {
        $this->__load();
        return parent::setDate($date);
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function setLocalisation($localisation)
    {
        $this->__load();
        return parent::setLocalisation($localisation);
    }

    public function getLocalisation()
    {
        $this->__load();
        return parent::getLocalisation();
    }

    public function addLaureat(\Ensat\GraduateBundle\Entity\LAUREAT $laureats)
    {
        $this->__load();
        return parent::addLaureat($laureats);
    }

    public function removeLaureat(\Ensat\GraduateBundle\Entity\LAUREAT $laureats)
    {
        $this->__load();
        return parent::removeLaureat($laureats);
    }

    public function getLaureats()
    {
        $this->__load();
        return parent::getLaureats();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'intitule', 'description', 'date', 'localisation', 'laureats');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}