<?php

namespace Ensat\GraduateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ADMINISTRATEURRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ADMINISTRATEURRepository extends EntityRepository
{
}
