<?php

namespace Ensat\GraduateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FILIERERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FILIERERepository extends EntityRepository
{
}
